#!/usr/bin/env python3
"""
build_log_replay.py
===================
Build Log Replay tool.

Reads a source of build-activity events and a target CSV
(`.github/build-logs/progressiov1-build-log.csv` by default), then appends
normalised entries with these guarantees:

1. **5-line preamble** — the output CSV always begins with exactly five
   descriptive header-comment lines before the column header row.
2. **Body hash per entry** — every data row carries an SHA-256 digest of its
   own body cells (all values excluding the leading timestamp column) so any
   modification to a logged event body is detectable without re-reading an
   external reference file.
3. **Remove duplicates** — an entry whose (source, ts, action, body_hash)
   tuple already exists in the tail of the active CSV is silently dropped.
4. **Align workers** — concurrent or out-of-order workers are grouped by
   `source` column and entries for the same source are written contiguously,
   preserving their timestamp order within the group rather than interleaving
   raw write times which would obscure linear reading of what one worker
   accomplished.

Source events come from two possible inputs (mutually exclusive):
  A) A JSONL file produced by the //build-log-entry slash command
     (one object per line with keys: ts, source, action, detail, worker_id).
  B) The programmatic API below — the module exposes `append_entry()` so
     callers (pipeline scripts, CI jobs) can directly submit records.

Usage examples:
    # Replay from a JSONL source file:
    python scripts/pipeline/build_log_replay.py --replay-from logs/build_events.jsonl

    # Append a single entry programmatically:
    from scripts.pipeline.build_log_replay import append_entry
    append_entry(
        ts="2026-07-10T16:00:00+00:00",
        source="pipeline/backfill_target.py",
        action="completed",
        detail="backfilled 145206 rows 2010-01-02 → 2026-07-10",
        worker_id="worker-A",
    )

    # Regenerate (wipe & replay from scratch):
    python scripts/pipeline/build_log_replay.py --replay-from logs/build_events.jsonl --wipe
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import os
import sys
import threading
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Constants & paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LOG_PATH = PROJECT_ROOT / ".github/build-logs/progressiov1-build-log.csv"
BACKUP_DIR = PROJECT_ROOT / ".github/build-logs/backups"
MANIFEST_PATH = BACKUP_DIR / "quarantine_manifest.json"

# 5-line preamble template (plain-text, does NOT use CSV comment marker
# so downstream tools don't accidentally drift; this is intentional).
PREAMBLE_LINES: list[str] = [
    "## Build Log — ProgressIO v1",
    "## Format: timestamp, source, action, detail, worker_id, dedup_signature, body_hash",
    "## WARNING: do not edit this file manually. Use build_log_replay.py or //build-log-entry.",
    f"## Generated: {datetime.now(timezone.utc).isoformat()}",
    "## Valid range: 2010-01-01 → 2027-12-31",
]

# Column order of the data section (line 6, immediately after preamble).
CSV_COLUMNS: list[str] = [
    "timestamp",
    "source",
    "action",
    "detail",
    "worker_id",
    "dedup_signature",
    "body_hash",
]

# Responsive threading lock guards the CSV during concurrent appends.
_WRITE_LOCK = threading.Lock()

# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def body_hash(cells: list[str], timestamp_col: str = "ts") -> str:  # noqa: ARG001
    """SHA-256 of the body cells joined by '|'.

    Body = all cells except the first (timestamp) element of the entry row,
    hashed deterministically so two identical bodies always produce the same
    digest regardless of the originating worker's write time.
    """
    body_text = "|".join(str(c).strip() for c in cells[1:])
    return hashlib.sha256(body_text.encode("utf-8", errors="replace")).hexdigest()


def dedup_signature(ts: str, source: str, action: str, body_hash: str) -> str:
    """Single shared digest used for deduplication lookups.

    Collapses the four de-facto identity fields (timestamp + source + action +
    body integrity) into a compact 32-char hex string that can be compared
    against existing rows without parsing structured fields.
    """
    raw = f"{ts}\x00{source}\x00{action}\x00{body_hash}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:64]


# ---------------------------------------------------------------------------
# In-memory store
# ---------------------------------------------------------------------------

class BuildLogStore:
    """Keeps the in-memory view of the active build log between appends.

    Workers call ``append()`` concurrently; the store serialises the final
    column order when the CSV is flushed to disk via ``write()``.
    """

    def __init__(self) -> None:
        # keyed by source; each value is a chronologically ordered list of
        # row dicts for that worker / source.
        self._groups: dict[str, list[dict[str, str]]] = defaultdict(list)
        self._seen: set[str] = set()  # dedup_signature values already stored

    # ---- public API ----

    def append(
        self,
        ts: str,
        source: str,
        action: str,
        detail: str,
        worker_id: str,
    ) -> dict[str, str] | None:
        """Register a new entry. Returns the row dict if added, None if dup."""
        rows_for_source = self._groups[source]
        b_hash = body_hash([ts, source, action, detail, worker_id])
        dsig = dedup_signature(ts, source, action, b_hash)

        # Also reject against full seen-set across all workers.
        if dsig in self._seen:
            return None

        # Within-source dedup: strip duplicates only against rows with the
        # same source (faster than full cross-worker check and matches the
        # "align workers" constraint).
        for existing in rows_for_source:
            if existing["dedup_signature"] == dsig:
                return None

        row: dict[str, str] = {
            "timestamp": ts,
            "source": source,
            "action": action,
            "detail": detail,
            "worker_id": worker_id,
            "dedup_signature": dsig,
            "body_hash": b_hash,
        }
        rows_for_source.append(row)
        self._seen.add(dsig)
        return row

    def ordered_rows(self) -> list[dict[str, str]]:
        """Return rows grouped by source, intra-source chronologically ordered."""
        result: list[dict[str, str]] = []
        for source in sorted(self._groups):
            result.extend(self._groups[source])
        return result

    # ---- persistence ----

    def write(self, path: Path, *, overwrite: bool = False) -> None:
        """Flush grouped rows to the CSV at *path*.

        File layout on disk (26 lines for 4 rows):
            [5-line preamble]
            timestamp,source,action,detail,worker_id,dedup_signature,body_hash
            2026-07-10T16:00:00,...,...
            ...
        """
        with _WRITE_LOCK:
            path.parent.mkdir(parents=True, exist_ok=True)

            # If file exists and not overwriting, load existing rows.
            if path.exists() and not overwrite:
                existing = _load_csv_body(path)
                for row in existing:
                    source = row["source"]
                    dsig = row["dedup_signature"]
                    if dsig not in self._seen:
                        self._groups[source].append(row)
                        self._seen.add(dsig)

            with open(path, "w", encoding="utf-8", newline="") as fh:
                # 1. Preamble
                for line in PREAMBLE_LINES:
                    fh.write(f"{line}\n")
                # 2. Blank separator — one empty line between preamble & header.
                fh.write("\n")
                # 3. Column header
                writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
                writer.writeheader()
                # 4. Data rows (grouped, aligned, deduplicated, with body hashes)
                writer.writerows(self.ordered_rows())


# ---------------------------------------------------------------------------
# CSV loader (body-only; skips preamble + header)
# ---------------------------------------------------------------------------

def _skip_preamble(fh: io.TextIOBase) -> None:
    """Advance file handle past the 5-line preamble and the blank line."""
    for _ in range(6):  # 5 preamble + 1 blank line
        fh.readline()
    fh.readline()  # column-header row


def _csv_rows(fh: io.TextIOBase) -> list[dict[str, str]]:
    reader = csv.DictReader(fh, fieldnames=CSV_COLUMNS)
    rows = [r for r in reader if any(v.strip() for v in r.values())]
    return rows


def _load_csv_body(path: Path) -> list[dict[str, str]]:
    with open(path, "r", encoding="utf-8") as fh:
        _skip_preamble(fh)
        return _csv_rows(fh)


# ---------------------------------------------------------------------------
# Public module-level API for slash commands and CI scripts
# ---------------------------------------------------------------------------

_GLOBAL_STORE: BuildLogStore | None = None
_LOCK = threading.Lock()


def _store() -> BuildLogStore:
    global _GLOBAL_STORE  # noqa: PLW0603
    if _GLOBAL_STORE is None:
        with _LOCK:
            _GLOBAL_STORE = BuildLogStore()
    return _GLOBAL_STORE


def append_entry(
    ts: str,
    source: str,
    action: str,
    detail: str,
    worker_id: str,
    *,
    log_path: str | Path = DEFAULT_LOG_PATH,
) -> dict[str, str] | None:
    """Append a single build-log entry; persist immediately.

    Returns the stored row dict if the entry is new, None if it is a
    duplicate or the file could not be written.

    This function is safe to call from multiple threads — the internal
    store is protected by a module-level lock, and the disk write is
    guarded by the class-level _WRITE_LOCK.
    """
    now_ts = ts or datetime.now(timezone.utc).isoformat()
    store = _store()
    row = store.append(
        ts=now_ts,
        source=source,
        action=action,
        detail=detail,
        worker_id=worker_id,
    )
    if row is None:
        return None

    log_path = Path(log_path)
    store.write(log_path)
    return row


def replay_from_jsonl(
    jsonl_path: str | Path,
    *,
    log_path: str | Path = DEFAULT_LOG_PATH,
    wipe: bool = False,
) -> dict[str, int]:
    """Replay a JSONL event file into the build log CSV.

    Returns a summary dict: { "total": N, "appended": A, "duplicates": D }.
    """
    jsonl_path = Path(jsonl_path)
    if not jsonl_path.is_file():
        print(f"[err] Source file not found: {jsonl_path}", file=sys.stderr)
        return {"total": 0, "appended": 0, "duplicates": 0}

    store = BuildLogStore()
    total = 0
    duplicates = 0
    with open(jsonl_path, "r", encoding="utf-8") as fh:
        for line_no, raw_line in enumerate(fh, 1):
            raw_line = raw_line.strip()
            if not raw_line:
                continue
            try:
                event = json.loads(raw_line)
            except json.JSONDecodeError as exc:
                print(f"[warn] JSON parse error on line {line_no}: {exc}", file=sys.stderr)
                continue
            total += 1
            result = store.append(
                ts=event.get("ts") or datetime.now(timezone.utc).isoformat(),
                source=event.get("source", "unknown"),
                action=event.get("action", "info"),
                detail=event.get("detail", ""),
                worker_id=event.get("worker_id", "worker-?"),
            )
            if result is None:
                duplicates += 1

    store.write(Path(log_path), overwrite=wipe)
    return {"total": total, "appended": total - duplicates, "duplicates": duplicates}


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _cli() -> None:
    ap = argparse.ArgumentParser(description="Build Log Replay tool")
    ap.add_argument(
        "--replay-from",
        type=str,
        required=False,
        help="JSONL source file to replay into the build log CSV",
    )
    ap.add_argument(
        "--log-path",
        type=str,
        default=str(DEFAULT_LOG_PATH),
        help=f"Output CSV path (default: {DEFAULT_LOG_PATH})",
    )
    ap.add_argument(
        "--wipe",
        action="store_true",
        help="Overwrite the target CSV entirely before replaying",
    )
    ap.add_argument(
        "--append",
        action="append",
        nargs=4,
        metavar=("TS", "SOURCE", "ACTION", "DETAIL"),
        help="Append a single entry directly from the CLI",
    )
    ap.add_argument(
        "--append-file",
        type=str,
        required=False,
        help="Append entries from a JSONL file (partial source, --wipe off)",
    )
    args = ap.parse_args()

    if (args.append_file or args.append) and args.replay_from:
        print("[err] Cannot combine --replay-from with --append / --append-file.", file=sys.stderr)
        raise SystemExit(1)

    if args.append_file:
        summary = replay_from_jsonl(
            args.append_file,
            log_path=args.log_path,
            wipe=args.wipe,
        )
        print(f"[ok] Replayed from {args.append_file}: "
              f"{summary['total']} total, {summary['appended']} new, {summary['duplicates']} dups")

    elif args.replay_from:
        summary = replay_from_jsonl(
            args.replay_from,
            log_path=args.log_path,
            wipe=args.wipe,
        )
        print(f"[ok] Replayed from {args.replay_from}: "
              f"{summary['total']} total, {summary['appended']} new, {summary['duplicates']} dups")

    elif args.append:
        for ts, source, action, detail in args.append:
            row = append_entry(ts, source, action, detail, worker_id="cli")
            tag = "dup" if row is None else "ok"
            print(f"[{tag}] {ts} | {source} | {action}: {detail}")
    else:
        ap.print_help()
        raise SystemExit(0)


if __name__ == "__main__":
    _cli()
